### ISSUE TITLE
Slide deck overview missing every 2nd slide

### ISSUE THREAD

**Issue by sven-frotscher** [Cimbali/pympress#311]
**Describe the bug**
When note slides are involved, the slide deck is missing every second slide.

**To Reproduce**
1. Create a TeX `beamer` presentation with `\setbeameroption{show notes on second screen}` (example source code attached below) and open the PDF in Pympress
2. `Presentation` - `Notes Position` and `Notes mode` seem to make no difference for this bug
3. Open `Presentation` - `Deck Overview`

Both slides and notes are displayed, but every second one is missing.
Selecting a slide out of the displayed ones works as expected though.

**Expected behavior**
Every slide is shown (preferably without associated notes).

**Screenshots**
![](https://github.com/Cimbali/pympress/assets/67124493/745ef43a-fd9a-49e1-b963-6d95ad2efe09)

**Environment**
 - OS: Endeavour OS (like Arch Linux)
 - Python version: 3.11.8-1
 - Pympress version: 1.8.5-1
 - Installation method: Arch repos

**Debug information**
Contents of `pympress.log`:
```
INFO:pympress.app:Pympress: 1.8.5 ; Python: 3.11.8 ; OS: Linux 6.7.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 ; Gtk 3.24.41 ; GLib 2.78.0 ; Poppler 24.03.0 cairo ; Cairo 1.18.0 , pycairo 1.26.0
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer 1.24.0, VLC not available
CRITICAL:pympress.__main__:Uncaught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pympress/config.py", line 506, in get_layout
    return self.layout[layout_name]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'deck'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pympress/ui.py", line 1815, in switch_mode
    self.load_layout(self.layout_name(target_mode))
  File "/usr/lib/python3.11/site-packages/pympress/ui.py", line 1755, in load_layout
    pane_handles = self.replace_layout(self.config.get_layout(new), self.p_central,
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pympress/config.py", line 508, in get_layout
    return self.static_layout[layout_name]
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'deck'
```

The problem still happens if I remove my config file, although it contains some additional lines in the `[notes position]` section when compared to the one Pympress auto-generates:
```
page number = after
page mapping = map
page parity = odd
```
The bug I'm describing seems unaffected by these entries.

**Additional context**
MWE TeX source code (change the file extension to `.tex`): [num-slides.txt](https://github.com/Cimbali/pympress/files/14601311/num-slides.txt)

My guess is that the deck overview only accounts for slides and notes on adjacent pages, not pages split between slide and notes.
The `CRITICAL` log entry only happened when I played around with some settings (e.g. toggling `Notes mode` while in the deck overview) and I doubt it's related.

**Comment by Cimbali** [comment]
The errors you’ve got in your logs are quite strange and should have prevented you from loading the deck view altogether. But aside from that can reproduce. It seems like the `deck` widget is understanding the wrong type of note pages (interleaved instead of second screen?)

**Comment by sven-frotscher** [comment]
> logged errors

The errors started when I toggled `Notes mode` in the deck view. Pympress got stuck in the deck view after that.

> deck widget understanding wrong type of note pages

Agreed.

**Comment by Cimbali** [comment]
Ok so this is fixed now. It was a combination of a number of rather subtle errors:
- your generated document has repeated page labels, as if it only had 2 pages each with a `\pause` command. Therefore, only showing 2 pages is actually intended.
  - This is something caused by the second screen mode, but can be disabled with `\documentclass[hyperref={pdfpagelabels=false}]{beamer}`. Alternately, pympress can be set to ignore page labels and always display all pages by setting `distinct-labels-only = off` in the `[deck-overview]` section of the config
- the deck respected the initial notes position, but didn’t get the updates (e.g. when guessed from the document), which means the full page (including second screen) was rendered instead of only the interesting part.
- the deck partially ignored the distinct-labels-only option I mentioned above.

**Comment by sven-frotscher** [comment]
Partially fixed (thank you, for what that's worth):
Only the presented slides are shown now (i.e. notes are hidden), but I still don't see slides 2 and 4 from my MWE in the deck overview.
#### Screenshot:
![Pympress screenshot](https://github.com/Cimbali/pympress/assets/67124493/9355a9a4-0d5b-434e-896a-c2e77b30c533)

**Comment by Cimbali** [comment]
As mentioned above, only showing 2 pages is actually intended. There are 2 ways to fix that, that I’ve listed there too.
